services:
  fastlivo2-ros2:
    image: crpi-6ty60rr45g7d9i1q.cn-shanghai.personal.cr.aliyuncs.com/voyance/fastlivo2_amd64:ros2
    container_name: fastlivo2-ros2
    stdin_open: true
    tty: true
    privileged: true
    network_mode: host
      #ports:
      #- 9090:9090
      #- 8778:8765
    environment:
      - ROS_DOMAIN_ID=10 
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
      - NVIDIA_DRIVER_CAPABILITIES=all
    devices:
      - /dev/video0:/dev/video0
      - /dev/dri:/dev/dri
    volumes:
      - ./start.sh:/opt/start.sh
      #- ../src:/root/fastlivo2/src
      - ../../dataset:/root/fastlivo2/dataset
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/tmp/.docker.xauth
      #- /opt/MVS:/opt/MVS
    command: [ "bash", "-c", "chmod +x /opt/start.sh && /opt/start.sh" ]
