/**:
    ros__parameters:
        feature_extract_enable: false
        point_filter_num: 5
        max_iteration: 5
        filter_size_surf: 0.5
        filter_size_map: 0.5
        cube_side_length: 1000.0
        runtime_pos_log_enable: true
        map_file_path: "./test.pcd"

        common:
            lid_topic:  "/main/ruby/lidar_points"
            imu_topic:  "/imu"
            time_sync_en: false              # ONLY turn on when external time synchronization is really not possible
            time_offset_lidar_to_imu: 0.0    # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
                                             # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0
            real_camera_init_en: true

        preprocess:
            lidar_type: 5                    # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
            scan_line: 32
            timestamp_unit: 3
            blind: 1.0
            scan_rate: 10

        mapping:
            acc_cov: 0.1
            gyr_cov: 0.1
            b_acc_cov: 0.0001
            b_gyr_cov: 0.0001
            fov_degree:    180.0
            det_range:     450.0
            extrinsic_est_en:  false         # true: enable the online estimation of IMU-LiDAR extrinsic
            # base_link 到 IMU 的外参
            # extrinsic_T_I2B: [  0.,  0.,  0.  ]      # 传感器的平移变换（单位：米）
            # extrinsic_R_I2B: [  1.,  0.,  0.,
            #                     0.,  1.,  0.,
            #                     0.,  0.,  1.  ]      # 传感器的旋转变换 （单位： 四元数或者旋转矩阵）
# W250917 11:06:14:679036	base_imu_gnss_processer.cc:60
# timestamp: 1.75593e+12 sequence: 20998frame_id: /imu
# I250917 11:06:14:679036	base_imu_gnss_processer.cc:68
#  -0.0201476    0.999795 -0.00219014    0.467101
#    0.999784   0.0201586  0.00514963 9.83622e-05
#  0.00519272 -0.00208592   -0.999984     1.22905
#           0           0           0           1
# I250917 11:06:14:679036	base_imu_gnss_processer.cc:69
#  -0.0201476    0.999784  0.00519272  0.00293048
#    0.999795   0.0201586 -0.00208592   -0.464443
# -0.00219014  0.00514963   -0.999984     1.23006
#          -0          -0          -0           1
            extrinsic_T_I2B: [   0.467101, 9.83622e-05,     1.22905 ]      # 传感器的平移变换（单位：米）
            extrinsic_R_I2B: [ -0.0201476,    0.999795, -0.00219014,
                                 0.999784,   0.0201586,  0.00514963,
                               0.00519272, -0.00208592,   -0.999984 ]      # 传感器的旋转变换 （单位： 四元数或者旋转矩阵）

            # LIDAR 到 IMU 的外参
            # 14081
            extrinsic_T: [  0.037, -0.000, -0.121 ]                        # 传感器的平移变换（单位：米）
            extrinsic_R: [ -0.037,  0.999, -0.006,
                            0.999,  0.037, -0.001,
                           -0.001, -0.006, -1.000]                         # 传感器的旋转变换 （单位： 四元数或者旋转矩阵）
            # pi
            # extrinsic_T: [  0.037, -0.000, -0.121 ]                      # 传感器的平移变换（单位：米）
            # extrinsic_R: [ -0.037,  0.999, -0.006,
            #                 0.999,  0.037, -0.001,
            #                 -0.001, -0.006, -1.000 ]                     # 传感器的旋转变换 （单位： 四元数或者旋转矩阵）

        publish:
            path_en:  true
            scan_publish_en:  true       # false: close all the point cloud output
            dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
            scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

        pcd_save:
            pcd_save_en: false
            interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                        # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
