/**:
  ros__parameters:
    camera:
      model: Pinhole
      width: 1920
      height: 1080
      scale: 0.4

# ./build-x86_v2.5/bin/test_image --frontend --logcout --loglevel 0
# pi
# W250905 13:29:27:382096	image_processer.cc:51 timestamp: 1.71601e+12 sequence: 26725 frame_id: /camera3
# I250905 13:29:27:382096	image_processer.cc:77 (w x h) = ( 1920 x 1080 )
# I250905 13:29:27:382096	image_processer.cc:78 [1187.04, 0, 989.444;
#  0, 1187.04, 507.182;
#  0, 0, 1]
# I250905 13:29:27:382096	image_processer.cc:79 [-0.4295989871025085;
#  0.3027920126914978;
#  -0.0002463890123181045;
#  -9.741930261952803e-05;
#  0.147707000374794;
#  0;
#  0;
#  0.3780179917812347]
# I250905 13:29:27:382096	image_processer.cc:80 0.000236294     0.01157    0.999933   0.0591772
#    -0.99986   -0.016729 0.000429844  0.00540323
#   0.0167328   -0.999793   0.0115644   -0.107346
#           0           0           0           1
      # fx: 1187.04
      # fy: 989.444
      # cx: 1187.04
      # cy: 507.182
      # d0: -0.4295989871025085
      # d1: 0.3027920126914978
      # d2: 0.147707000374794
      # d3: 0.3780179917812347

# 14081
# W250902 21:59:36:115430	image_processer.cc:51 timestamp: 1.75593e+12 sequence: 1219 frame_id: /front/1/stereo
# I250902 21:59:36:115430	image_processer.cc:77 (w x h) = ( 1920 x 1080 )
# I250902 21:59:36:115430	image_processer.cc:78 [1149.310059, 0, 974.762024;
#  0, 1149.339966, 551.377991;
#  0, 0, 1]
# I250902 21:59:36:115430	image_processer.cc:79 [-0.3665460050106049;
#  0.207736000418663;
#  0;
#  0;
#  0.05551299825310707;
#  0;
#  0;
#  0.1727239936590195]
# I250902 21:59:36:115430	image_processer.cc:80 -0.00961347  -0.0132553    0.999866    0.894635
#   -0.999928  0.00729468 -0.00951736    0.198027
# -0.00716754   -0.999886  -0.0133245   -0.512303
#           0           0           0           1
      fx: 1149.310059
      fy: 974.762024
      cx: 1149.339966
      cy: 551.377991
      d0: -0.3665460050106049
      d1: 0.207736000418663
      d2: 0.05551299825310707
      d3: 0.1727239936590195