/**:
  ros__parameters:
    common:                           # 通用配置
      img_topic: "/left_camera/image" # 相机图像话题
      lid_topic: "/livox/lidar"       # LiDAR 话题
      imu_topic: "/livox/imu"         # IMU 话题
      img_en: 1                       # 是否启用相机
      lidar_en: 1                     # 是否启用LiDAR
      ros_driver_bug_fix: false       # 是否启用ROS驱动Bug 修复
      real_camera_init_en: 0          # 是否将camera_init映射到真实空间中

    extrin_calib:                                            # 外参标定参数
      # base_link 到 IMU 的外参
      extrinsic_T_I2B: [  0., 0.,  0. ]                      # 传感器的平移变换（单位：米）
      extrinsic_R_I2B: [  1., 0.,  0.,
                          0., 1.,  0.,
                          0., 0.,  1. ]                      # 传感器的旋转变换 （单位： 四元数或者旋转矩阵）
      extrinsic_T: [-0.011, -0.02329, 0.04412]
      extrinsic_R: [1.0, 0.0, 0.0,
                    0.0, 1.0, 0.0,
                    0.0, 0.0, 1.0]
      Rcl: [0.00910, -0.99992, 0.00868,
            0.44077, -0.00378, -0.89761,
            0.89757, 0.01199, 0.44070]                        # 相机到LiDAR的旋转矩阵
      Pcl: [0.01730, -0.07362, -0.01012]                      # 相机到liDAR的平移矩阵（单位：米）

    time_offset:                                             # 传感器时间同步参数
      imu_time_offset: 0.0                                   # IMU 时间偏移（单位：秒）
      img_time_offset: 0.1                                   # 相机 时间偏移（单位：秒）
      exposure_time_init: 0.0                                # 初始曝光时间 （单位：秒）

    preprocess:                                              # 预处理参数
      point_filter_num: 1                                    # 点云滤波次数
      filter_size_surf: 0.1                                  # 表面滤波尺寸（单位：米）
      lidar_type: 1                                          # LiDAR 类型 Livox Avia LiDAR
      scan_line: 4                                           # 扫描线数量（Avia：6， Mid360：4）
      blind: 0.8                                             # LiDAR盲区范围（单位：米）

    vio:                                                     # 视觉惯性里程计（VIO） 参数
      max_iterations: 5                                      # 最大迭代次数
      outlier_threshold: 1000                                # 离群点阈值 78 100 156 #100 200 500 700 infinite
      img_point_cov: 100                                     # 图像特征点协方差 100 1000 
      patch_size: 8                                          # 视觉特征块大小
      patch_pyrimid_level: 4                                 # 视觉金字塔层级数
      normal_en: true                                        # 是否启用法向量计算
      raycast_en: false                                      # 是否启用光线投射
      inverse_composition_en: false                          # 是否使用逆组合方法
      exposure_estimate_en: true                             # 是否启用曝光时间估计
      inv_expo_cov: 0.1                                      # 曝光时间估计协方差

    imu:                                                     # IMU相关参数
      imu_en: true                                           # 是否启用
      imu_int_frame: 100                                     # IMU初始化帧数
      acc_cov: 0.5                                           # 加速度计噪声协方差 0.2
      gyr_cov: 0.3                                           # 陀螺仪噪声协方差 0.5
      b_acc_cov: 0.0001                                      # 加速度偏差噪声协方差 0.1
      b_gyr_cov: 0.0001                                      # 陀螺仪偏差噪声协方差 0.1

    lio:                                                     # 激光惯性里程计（LIO） 参数
      max_iterations: 5                                      # 最大迭代次数
      dept_err: 0.02                                         # 深度误差（单位：米）
      beam_err: 0.05                                         # 光速误差（单位：米）
      min_eigen_value: 0.0025                                # 最小特征值 0.005
      voxel_size: 0.5                                        # 体素滤波尺寸（单位：米）
      max_layer: 2                                           # 最大层数
      max_points_num: 50                                     # 最大点数
      layer_init_num: [5, 5, 5, 5, 5]                        # 各层初始化点数

    local_map:                                               # 局部地图参数
      map_sliding_en: true                                   # 是否启用滑动窗口地图
      half_map_size: 100                                     # 地图窗口半径（单位：米）
      sliding_thresh: 8.0                                    # 地图滑动阈值（单位：米）

    uav:                                                     # 无人机相关参数
      imu_rate_odom: false                                   # 是否根据IMU频率发布里程计数据
      gravity_align_en: true                                 # 是否启用重力对齐

    publish:                                                 # 话题发布相关开关
      dense_map_en: false                                    # 是否发布精密点云地图
      pub_effect_point_en: true                              # 是否发布有效点云
      pub_plane_en: false                                    # 是否发布平面点云
      pub_scan_num: 5                                        # 需要发布的扫描间隔次数
      blind_rgb_points: 0.0                                  # RGB 盲区点云

    evo:                                                     # 轨迹评估相关参数
      seq_name: "CBD_Building_01"                            # 轨迹数据集名称
      pose_output_en: false                                  # 是否输出位姿数据

    pcd_save:                                                # 点云数据保存参数
      pcd_save_en: false                                     # 是否启用点云保存
      colmap_output_en: false                                # 是否输出至 COLMAP need to set interval = -1
      filter_size_pcd: 0.15                                  # 点云滤波尺寸（单位：米）
      interval: -1                                           # 点云保存间隔（-1 表示所有帧保存到一个PCD问价，可能导致内存溢出）
      # how many LiDAR frames saved in each pcd file;
      # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
